# Generated by Django 6.0.3 on 2026-07-23 06:32

import django.db.models.deletion
import django.utils.timezone
import prospeccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_proposal_accepted_consents_proposal_accepted_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('salon', 'Salón de belleza / peluquería / estética'), ('bar', 'Bar / cafetería / restaurante'), ('taller', 'Taller / automoción / servicio técnico'), ('academia', 'Academia / cursos / formación'), ('clinica', 'Clínica / fisioterapia / salud privada'), ('tienda', 'Tienda local'), ('inmobiliaria', 'Inmobiliaria / reformas / servicios profesionales'), ('otro', 'Otro negocio local')], default='otro', max_length=30)),
                ('sales_status', models.CharField(choices=[('discovered', 'Descubierto'), ('pre_audited', 'Pre-auditado'), ('contacted', 'Contactado'), ('audited', 'Auditado'), ('presupuesto_created', 'Presupuesto creado'), ('won', 'Ganado'), ('lost', 'Perdido'), ('do_not_contact', 'No contactar'), ('archived', 'Archivado')], db_index=True, default='discovered', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=10)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('needs_manual_placement', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('gmaps_url', models.CharField(blank=True, max_length=500)),
                ('has_website', models.BooleanField(blank=True, null=True)),
                ('has_online_booking', models.BooleanField(blank=True, null=True)),
                ('has_whatsapp_cta', models.BooleanField(blank=True, null=True)),
                ('current_score', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('map_click', 'Clic en el mapa'), ('csv_import', 'Importación CSV'), ('public_quiz_upgrade', 'Chequeo público')], default='manual', max_length=30)),
                ('staff_notes', models.TextField(blank=True)),
                ('public_token', models.CharField(db_index=True, default=prospeccion.models._new_token, max_length=64, unique=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('publish_consent', models.BooleanField(default=False)),
                ('publish_confirmed_by_staff', models.BooleanField(default=False)),
                ('publish_consent_at', models.DateTimeField(blank=True, null=True)),
                ('publish_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospeccion_source', to='crm.lead')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='prospeccion.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('owner', 'Dueño/a'), ('manager', 'Gerente'), ('administrator', 'Administración'), ('employee', 'Empleado/a'), ('marketing', 'Marketing')], default='owner', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Teléfono')], default='whatsapp', max_length=20)),
                ('consent_receive_report', models.BooleanField(default=False)),
                ('consent_receive_report_at', models.DateTimeField(blank=True, null=True)),
                ('consent_receive_report_method', models.CharField(blank=True, max_length=50)),
                ('consent_commercial_contact', models.BooleanField(default=False)),
                ('consent_commercial_contact_at', models.DateTimeField(blank=True, null=True)),
                ('consent_commercial_contact_method', models.CharField(blank=True, max_length=50)),
                ('consent_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='prospeccion.businessprospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChequeoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('public', 'Público'), ('personal', 'Personal')], default='public', max_length=10)),
                ('stage', models.CharField(choices=[('preliminar', 'Preliminar'), ('confirmado', 'Confirmado')], default='preliminar', max_length=15)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sector', models.CharField(choices=[('salon', 'Salón de belleza / peluquería / estética'), ('bar', 'Bar / cafetería / restaurante'), ('taller', 'Taller / automoción / servicio técnico'), ('academia', 'Academia / cursos / formación'), ('clinica', 'Clínica / fisioterapia / salud privada'), ('tienda', 'Tienda local'), ('inmobiliaria', 'Inmobiliaria / reformas / servicios profesionales'), ('otro', 'Otro negocio local')], max_length=30)),
                ('questionnaire_version', models.CharField(max_length=20)),
                ('answers', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('category_scores', models.JSONField(default=dict)),
                ('good_ids', models.JSONField(default=list)),
                ('fix_ids', models.JSONField(default=list)),
                ('sector_benchmark', models.IntegerField(default=75)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='prospeccion.businessprospect')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prospect', '-created_at'], name='prospeccion_prospec_f6fb49_idx'), models.Index(fields=['session_key'], name='prospeccion_session_a9ab89_idx')],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('visit', 'Visita'), ('call', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('quiz_started', 'Chequeo iniciado'), ('quiz_completed', 'Chequeo completado'), ('report_sent', 'Informe enviado'), ('meeting', 'Reunión'), ('presupuesto_created', 'Presupuesto creado'), ('won', 'Ganado'), ('lost', 'Perdido')], max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=300)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='prospeccion.businessprospect')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospeccion.staffmember')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['prospect', 'date'], name='prospeccion_prospec_1a7cec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='businessprospect',
            index=models.Index(fields=['lat', 'lng'], name='prospeccion_lat_5d9721_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprospect',
            index=models.Index(fields=['sector', 'sales_status'], name='prospeccion_sector_fdf0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprospect',
            index=models.Index(fields=['assigned_to', 'next_action_at'], name='prospeccion_assigne_b25da4_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprospect',
            index=models.Index(fields=['publish_consent', 'publish_confirmed_by_staff'], name='prospeccion_publish_00d6a1_idx'),
        ),
    ]
