# Generated by Django 6.0.3 on 2026-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontact',
            name='consent_revoked_at',
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='consent_commercial_contact_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='consent_receive_report_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='can_confirm_publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño/a'), ('manager', 'Gerente'), ('administrator', 'Administración'), ('employee', 'Empleado/a'), ('marketing', 'Marketing'), ('unknown', 'Desconocido')], default='owner', max_length=20),
        ),
    ]
