# Generated by Django 6.0.3 on 2026-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0002_remove_businesscontact_consent_revoked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='consent_commercial_contact_actor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='consent_commercial_contact_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='consent_receive_report_actor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='consent_receive_report_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
