# Generated by Django 6.0.3 on 2026-07-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0003_businesscontact_consent_commercial_contact_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='businessprospect',
            name='google_place_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='businessprospect',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('map_click', 'Clic en el mapa'), ('csv_import', 'Importación CSV'), ('public_quiz_upgrade', 'Chequeo público'), ('google_places', 'Búsqueda de Google Places')], default='manual', max_length=30),
        ),
    ]
