# Generated by Django 6.0.3 on 2026-07-24 19:00

import prospeccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0004_placesapiusage_businessprospect_google_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeoaudit',
            name='report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeoaudit',
            name='report_token',
            field=models.CharField(db_index=True, default=prospeccion.models._new_token, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='chequeoaudit',
            name='respondent_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeoaudit',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
