# Generated by Django 6.0.3 on 2026-07-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0005_chequeoaudit_report_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prospeccion_fotos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_photos', to='prospeccion.businessprospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
