# Generated by Django 6.0.3 on 2026-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_lead_source'),
        ('prospeccion', '0006_prospectphoto'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessprospect',
            name='prospeccion_publish_00d6a1_idx',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='can_confirm_publication',
        ),
        migrations.AddIndex(
            model_name='businessprospect',
            index=models.Index(fields=['publish_consent'], name='prospeccion_publish_c6b4f8_idx'),
        ),
        migrations.RemoveField(
            model_name='businessprospect',
            name='publish_confirmed_by_staff',
        ),
    ]
