# Generated by Django 6.0.3 on 2026-08-01 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0007_remove_businessprospect_prospeccion_publish_00d6a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesApiLimitNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.CharField(db_index=True, max_length=7)),
                ('request_type', models.CharField(choices=[('text_search_enterprise', 'Text Search — Enterprise'), ('nearby_search_enterprise', 'Nearby Search — Enterprise'), ('place_details_enterprise', 'Place Details — Enterprise'), ('place_details_enterprise_atmosphere', 'Place Details — Enterprise + Atmosphere'), ('text_search_pro', 'Text Search — Pro'), ('nearby_search_pro', 'Nearby Search — Pro'), ('legacy_unknown', 'Histórico sin desglosar (anterior a este control)')], max_length=40)),
                ('threshold', models.PositiveSmallIntegerField()),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('billing_month', 'request_type', 'threshold'), name='uniq_places_notif_month_type_threshold')],
            },
        ),
        migrations.CreateModel(
            name='PlacesApiMonthlyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.CharField(db_index=True, max_length=7)),
                ('request_type', models.CharField(choices=[('text_search_enterprise', 'Text Search — Enterprise'), ('nearby_search_enterprise', 'Nearby Search — Enterprise'), ('place_details_enterprise', 'Place Details — Enterprise'), ('place_details_enterprise_atmosphere', 'Place Details — Enterprise + Atmosphere'), ('text_search_pro', 'Text Search — Pro'), ('nearby_search_pro', 'Nearby Search — Pro'), ('legacy_unknown', 'Histórico sin desglosar (anterior a este control)')], db_index=True, max_length=40)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('billing_month', 'request_type'), name='uniq_places_counter_month_type')],
            },
        ),
        migrations.CreateModel(
            name='PlacesApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('billing_month', models.CharField(db_index=True, max_length=7)),
                ('request_type', models.CharField(choices=[('text_search_enterprise', 'Text Search — Enterprise'), ('nearby_search_enterprise', 'Nearby Search — Enterprise'), ('place_details_enterprise', 'Place Details — Enterprise'), ('place_details_enterprise_atmosphere', 'Place Details — Enterprise + Atmosphere'), ('text_search_pro', 'Text Search — Pro'), ('nearby_search_pro', 'Nearby Search — Pro'), ('legacy_unknown', 'Histórico sin desglosar (anterior a este control)')], db_index=True, max_length=40)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=120)),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('query_hash', models.CharField(blank=True, max_length=64)),
                ('coordinates_hash', models.CharField(blank=True, max_length=64)),
                ('radius_m', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospeccion.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['billing_month', 'request_type'], name='prospeccion_billing_00411b_idx')],
            },
        ),
    ]
