# Generated by Django 6.0.3 on 2026-06-30 23:04

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatsession_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='short_id',
            field=models.CharField(default=core.models._gen_short_id, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='WaMessageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_msgs', to='core.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
