# Generated by Django 6.0.3 on 2026-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chatsession_short_id_wamessagemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='operator_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='template_sent',
            field=models.BooleanField(default=False),
        ),
    ]
