# Generated by Django 6.0.3 on 2026-07-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('biz_type', models.CharField(blank=True, max_length=100)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('package_base_price', models.IntegerField(default=0)),
                ('extras', models.JSONField(default=list)),
                ('extras_price', models.IntegerField(default=0)),
                ('rush', models.BooleanField(default=False)),
                ('maintenance_plan', models.CharField(blank=True, max_length=50)),
                ('maintenance_price', models.IntegerField(default=0)),
                ('estimated_price', models.IntegerField(default=0)),
                ('discount_pct', models.IntegerField(default=15)),
                ('source', models.CharField(choices=[('calculator', 'Calculadora'), ('contact_form', 'Formulario de contacto'), ('chat', 'Chat en vivo'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual')], default='calculator', max_length=30)),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('propuesta_enviada', 'Propuesta enviada'), ('negociacion', 'Negociación'), ('aceptado', 'Aceptado'), ('en_trabajo', 'En trabajo'), ('finalizado', 'Finalizado'), ('perdido', 'Perdido')], default='nuevo', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
