# Generated by Django 6.0.3 on 2026-07-01 23:11

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='preferred_channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('both', 'WhatsApp + Email')], default='whatsapp', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_required', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Saliente'), ('inbound', 'Entrante')], max_length=10)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('portal', 'Portal'), ('manual', 'Manual')], max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='sent', max_length=20)),
                ('wamid', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_log', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=crm.models._material_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Video'), ('logo', 'Logo / imagen corporativa'), ('text', 'Texto / contenido'), ('document', 'Documento'), ('other', 'Otro')], default='other', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('portal', 'Portal cliente'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('manual', 'Subida manualmente')], default='portal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
