# Generated by Django 6.0.3 on 2026-07-01 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_preferred_channel_clientaccess_communicationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('viewed', 'Vista'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='draft', max_length=20)),
                ('valid_days', models.IntegerField(default=15)),
                ('issued_at', models.DateField()),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.CharField(blank=True, max_length=200)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('client_biz_type', models.CharField(blank=True, max_length=100)),
                ('client_nif', models.CharField(blank=True, max_length=30)),
                ('client_address', models.CharField(blank=True, max_length=300)),
                ('client_city', models.CharField(blank=True, max_length=100)),
                ('company_data', models.JSONField(default=dict)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_goal', models.TextField(blank=True)),
                ('biz_description', models.TextField(blank=True)),
                ('selected_features', models.TextField(blank=True)),
                ('scope', models.JSONField(default=list)),
                ('out_of_scope', models.JSONField(default=list)),
                ('phases', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(default='50-50', max_length=30)),
                ('payment_custom', models.TextField(blank=True)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('package_base_price', models.IntegerField(default=0)),
                ('extras', models.JSONField(default=list)),
                ('extras_price', models.IntegerField(default=0)),
                ('rush', models.BooleanField(default=False)),
                ('rush_amount', models.IntegerField(default=0)),
                ('discount_pct', models.IntegerField(default=15)),
                ('discount_amount', models.IntegerField(default=0)),
                ('taxable_base', models.IntegerField(default=0)),
                ('iva_pct', models.IntegerField(default=21)),
                ('iva_amount', models.IntegerField(default=0)),
                ('total_with_iva', models.IntegerField(default=0)),
                ('maintenance_plan', models.CharField(blank=True, max_length=50)),
                ('maintenance_price', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by_name', models.CharField(blank=True, max_length=200)),
                ('accepted_nif', models.CharField(blank=True, max_length=30)),
                ('accepted_signature', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
