# Generated by Django 6.0.3 on 2026-07-02 00:00

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('screenshot', 'Captura de pantalla'), ('invoice', 'Factura'), ('approval', 'Aprobación del cliente'), ('contract', 'Contrato'), ('delivery', 'Entregable'), ('other', 'Otro')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to=crm.models._evidence_upload_path)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('bizum', 'Bizum'), ('paypal', 'PayPal'), ('cash', 'Efectivo'), ('stripe', 'Stripe'), ('other', 'Otro')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=crm.models._invoice_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibido'), ('partial', 'Parcial'), ('refunded', 'Devuelto')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.lead')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('done', 'Completado'), ('blocked', 'Bloqueado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='crm.lead')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('category', models.CharField(choices=[('design', 'Diseño'), ('development', 'Desarrollo'), ('content', 'Contenido'), ('meeting', 'Reunión'), ('revision', 'Revisión'), ('delivery', 'Entrega'), ('other', 'Otro')], default='development', max_length=20)),
                ('description', models.TextField()),
                ('deliverable_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='crm.lead')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
