# Generated by Django 6.0.3 on 2026-07-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_activity_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='reactions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='crm.communicationlog'),
        ),
    ]
