# Generated by Django 6.0.3 on 2026-07-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_communicationlog_deleted_communicationlog_reactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='admin_chat_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
