# Generated by Django 6.0.3 on 2026-07-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_lead_admin_chat_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hosting_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='hours_plan_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='hours_plan_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='hosting_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='hours_plan_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='hours_plan_price',
            field=models.IntegerField(default=0),
        ),
    ]
