# Generated by Django 6.0.3 on 2026-07-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_hosting_price_lead_hours_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accepted_consents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='proposals/accepted/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted_pdf_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted_user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_country',
            field=models.CharField(blank=True, default='España', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_type',
            field=models.CharField(blank=True, choices=[('particular', 'Particular (consumidor)'), ('autonomo', 'Autónomo'), ('empresa', 'Empresa')], max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='representative_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='representative_nif',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='representative_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='crm.proposal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='withdrawal_waived',
            field=models.BooleanField(default=False),
        ),
    ]
