# Generated by Django 6.0.3 on 2026-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_proposal_accepted_consents_proposal_accepted_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('calculator', 'Calculadora'), ('contact_form', 'Formulario de contacto'), ('chat', 'Chat en vivo'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual'), ('mapa_digital', 'Mapa Digital')], default='calculator', max_length=30),
        ),
    ]
