# Generated by Django 6.0.3 on 2026-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project_db_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
