# Generated by Django 6.0.3 on 2026-08-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_project_db_path_lead_project_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('portal', 'Портал'), ('manual', 'Вручную')], max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Исходящее'), ('inbound', 'Входящее')], max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='category',
            field=models.CharField(choices=[('screenshot', 'Скриншот'), ('invoice', 'Счёт'), ('approval', 'Одобрение клиента'), ('contract', 'Договор'), ('delivery', 'Сдача проекта'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('calculator', 'Калькулятор'), ('contact_form', 'Форма контакта'), ('chat', 'Онлайн-чат'), ('whatsapp', 'WhatsApp'), ('manual', 'Вручную'), ('mapa_digital', 'Карта Digital')], default='calculator', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Новый'), ('contactado', 'На связи'), ('propuesta_enviada', 'Предложение отправлено'), ('negociacion', 'Переговоры'), ('aceptado', 'Принято'), ('en_trabajo', 'В работе'), ('finalizado', 'Завершено'), ('perdido', 'Потеряно')], default='nuevo', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Банковский перевод'), ('bizum', 'Bizum'), ('paypal', 'PayPal'), ('cash', 'Наличные'), ('stripe', 'Stripe'), ('other', 'Другое')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('received', 'Получено'), ('partial', 'Частично'), ('refunded', 'Возвращено')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('logo', 'Логотип / фирменный стиль'), ('text', 'Текст / контент'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='source',
            field=models.CharField(choices=[('portal', 'Портал клиента'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('manual', 'Загружено вручную')], default='portal', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('done', 'Готово'), ('blocked', 'Заблокировано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('viewed', 'Просмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='category',
            field=models.CharField(choices=[('design', 'Дизайн'), ('development', 'Разработка'), ('content', 'Контент'), ('meeting', 'Встреча'), ('revision', 'Правки'), ('delivery', 'Сдача'), ('other', 'Другое')], default='development', max_length=20),
        ),
    ]
