# Generated by Django 6.0.3 on 2026-07-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('ventas', 'Ventas y prospección'), ('contenido', 'Contenido y marketing'), ('estrategia', 'Estrategia y negocio'), ('finanzas', 'Finanzas'), ('perfil', 'Marca personal'), ('personal', 'Día personal'), ('habito', 'Hábito diario'), ('cierre', 'Cierre de mes')], max_length=20)),
                ('default_points', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('custom_title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('ventas', 'Ventas y prospección'), ('contenido', 'Contenido y marketing'), ('estrategia', 'Estrategia y negocio'), ('finanzas', 'Finanzas'), ('perfil', 'Marca personal'), ('personal', 'Día personal'), ('habito', 'Hábito diario'), ('cierre', 'Cierre de mes')], max_length=20)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='planner.taskcatalogitem')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='planner.calendarentry')),
            ],
        ),
    ]
