# Generated by Django 6.0.3 on 2026-07-17 11:38

import django.db.models.deletion
import planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(default=planner.models._generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='girl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planner.girl'),
        ),
    ]
