# Generated by Django 6.0.3 on 2026-07-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_backfill_girl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarentry',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planner.girl'),
        ),
    ]
