# Generated by Django 6.0.3 on 2026-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
