# Generated by Django 6.0.3 on 2026-07-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_girl_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='monthly_goal',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='girl',
            name='motto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='girl',
            name='points_target',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.CreateModel(
            name='GirlMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planner.girl')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
