# Generated by Django 6.0.3 on 2026-07-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_girl_monthly_goal_girl_motto_girl_points_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='girlmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='girlmessage',
            name='reaction',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='girlmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='planner.girlmessage'),
        ),
        migrations.AddField(
            model_name='girlmessage',
            name='sender',
            field=models.CharField(choices=[('admin', 'Ekaterina'), ('girl', 'Alumna')], default='admin', max_length=10),
        ),
    ]
