# Generated by Django 6.0.3 on 2026-07-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_girlmessage_options_girlmessage_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='general_chat_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='girl',
            name='general_chat_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneralMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Ekaterina'), ('girl', 'Alumna')], max_length=10)),
                ('text', models.TextField()),
                ('reaction', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='planner.generalmessage')),
                ('sender_girl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_messages', to='planner.girl')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
