# Generated by Django 6.0.3 on 2026-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_adminsettings_general_chat_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalmessage',
            name='sender_type',
            field=models.CharField(choices=[('admin', 'Katerina'), ('girl', 'Alumna')], max_length=10),
        ),
        migrations.AlterField(
            model_name='girlmessage',
            name='sender',
            field=models.CharField(choices=[('admin', 'Katerina'), ('girl', 'Alumna')], default='admin', max_length=10),
        ),
    ]
